-- V1.0 KJV reader content catalog schema.
-- This migration creates structure only; it intentionally does not import Bible text.

create table public.translations (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  abbreviation text not null,
  name text not null,
  language_code text not null default 'en',
  versification text not null default 'kjv',
  copyright_notice text,
  rights_statement text,
  is_public_domain boolean not null default false,
  is_enabled boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint translations_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint translations_abbreviation_present check (btrim(abbreviation) <> ''),
  constraint translations_name_present check (btrim(name) <> ''),
  constraint translations_language_code_format check (language_code ~ '^[a-z]{2,3}(-[A-Z]{2})?$')
);

create table public.books (
  id bigint generated by default as identity primary key,
  osis_id text not null unique,
  slug text not null unique,
  name text not null,
  common_abbreviation text,
  testament text not null,
  book_order smallint not null unique,
  chapters_count smallint not null,
  created_at timestamptz not null default now(),

  constraint books_osis_id_present check (btrim(osis_id) <> ''),
  constraint books_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint books_name_present check (btrim(name) <> ''),
  constraint books_testament_valid check (testament in ('old', 'new')),
  constraint books_book_order_range check (book_order between 1 and 66),
  constraint books_chapters_count_positive check (chapters_count > 0)
);

create table public.data_sources (
  id bigint generated by default as identity primary key,
  translation_id bigint references public.translations(id) on delete restrict,
  source_key text not null unique,
  source_type text not null,
  title text not null,
  url text,
  license text,
  attribution text,
  checksum_sha256 text,
  imported_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint data_sources_source_key_format check (source_key ~ '^[a-z0-9]+(?:[-_/][a-z0-9]+)*$'),
  constraint data_sources_source_type_valid check (source_type in ('manuscript', 'digital_text', 'metadata', 'cross_reference', 'other')),
  constraint data_sources_title_present check (btrim(title) <> ''),
  constraint data_sources_url_http check (url is null or url ~ '^https?://'),
  constraint data_sources_checksum_sha256_format check (checksum_sha256 is null or checksum_sha256 ~ '^[a-f0-9]{64}$')
);

create table public.verses (
  id bigint generated by default as identity primary key,
  translation_id bigint not null references public.translations(id) on delete restrict,
  book_id bigint not null references public.books(id) on delete restrict,
  chapter_number smallint not null,
  verse_number smallint not null,
  verse_text text not null,
  pilcrow_marker boolean not null default false,
  words_of_christ boolean not null default false,
  source_id bigint references public.data_sources(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint verses_chapter_number_positive check (chapter_number > 0),
  constraint verses_verse_number_positive check (verse_number > 0),
  constraint verses_verse_text_present check (btrim(verse_text) <> ''),
  constraint verses_translation_book_chapter_verse_unique unique (translation_id, book_id, chapter_number, verse_number)
);

create index books_testament_order_idx on public.books (testament, book_order);
create index data_sources_translation_id_idx on public.data_sources (translation_id);
create index verses_book_chapter_idx on public.verses (book_id, chapter_number, verse_number);
create index verses_translation_book_chapter_idx on public.verses (translation_id, book_id, chapter_number, verse_number);
create index verses_source_id_idx on public.verses (source_id) where source_id is not null;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger set_translations_updated_at
before update on public.translations
for each row execute function public.set_updated_at();

create trigger set_data_sources_updated_at
before update on public.data_sources
for each row execute function public.set_updated_at();

create trigger set_verses_updated_at
before update on public.verses
for each row execute function public.set_updated_at();

alter table public.translations enable row level security;
alter table public.books enable row level security;
alter table public.data_sources enable row level security;
alter table public.verses enable row level security;

grant select on public.translations to anon, authenticated;
grant select on public.books to anon, authenticated;
grant select on public.data_sources to anon, authenticated;
grant select on public.verses to anon, authenticated;

create policy "Public can read enabled translations"
on public.translations
for select
to anon, authenticated
using (is_enabled = true);

create policy "Public can read canonical books"
on public.books
for select
to anon, authenticated
using (true);

create policy "Public can read sources for enabled translations"
on public.data_sources
for select
to anon, authenticated
using (
  translation_id is null
  or exists (
    select 1
    from public.translations
    where translations.id = data_sources.translation_id
      and translations.is_enabled = true
  )
);

create policy "Public can read verses for enabled translations"
on public.verses
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.translations
    where translations.id = verses.translation_id
      and translations.is_enabled = true
  )
);

comment on table public.translations is 'Bible translation catalog entries for the reader. V1.0 targets KJV, but no Bible text is imported by this migration.';
comment on table public.books is 'Canonical Bible book metadata shared by translations.';
comment on table public.data_sources is 'Provenance records for translation metadata and future verse imports.';
comment on table public.verses is 'Verse text storage keyed by translation, book, chapter, and verse. Empty until an import migration or job loads Bible text.';
