-- Add chapter metadata and full-text search support for the KJV reader.

create table public.chapters (
  id bigint generated by default as identity primary key,
  book_id bigint not null references public.books(id) on delete restrict,
  chapter_number smallint not null,
  verse_count smallint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint chapters_chapter_number_positive check (chapter_number > 0),
  constraint chapters_verse_count_positive check (verse_count > 0),
  constraint chapters_book_chapter_unique unique (book_id, chapter_number)
);

create index chapters_book_chapter_idx on public.chapters (book_id, chapter_number);

create trigger set_chapters_updated_at
before update on public.chapters
for each row execute function public.set_updated_at();

alter table public.chapters enable row level security;

grant select on public.chapters to anon, authenticated;

create policy "Public can read canonical chapters"
on public.chapters
for select
to anon, authenticated
using (true);

alter table public.verses
add column search_vector tsvector generated always as (to_tsvector('english', verse_text)) stored;

create index verses_search_vector_idx on public.verses using gin (search_vector);

create or replace function public.search_kjv_verses(search_query text, result_limit integer default 20)
returns table (
  book_slug text,
  book_name text,
  book_order smallint,
  chapter_number smallint,
  verse_number smallint,
  translation_slug text,
  translation_abbreviation text,
  verse_text text,
  rank real
)
language sql
stable
set search_path = public
as $$
  with query_input as (
    select websearch_to_tsquery('english', btrim(search_query)) as query
    where btrim(coalesce(search_query, '')) <> ''
  )
  select
    b.slug as book_slug,
    b.name as book_name,
    b.book_order,
    v.chapter_number,
    v.verse_number,
    tr.slug as translation_slug,
    tr.abbreviation as translation_abbreviation,
    v.verse_text,
    ts_rank_cd(v.search_vector, query_input.query) as rank
  from query_input
  join public.translations tr on tr.slug = 'kjv' and tr.is_enabled = true
  join public.verses v on v.translation_id = tr.id
  join public.books b on b.id = v.book_id
  where v.search_vector @@ query_input.query
  order by rank desc, b.book_order, v.chapter_number, v.verse_number
  limit least(greatest(coalesce(result_limit, 20), 1), 50);
$$;

grant execute on function public.search_kjv_verses(text, integer) to anon, authenticated;

comment on table public.chapters is 'Canonical chapter metadata used by the Bible reader selectors.';
comment on function public.search_kjv_verses(text, integer) is 'Full-text KJV verse search over enabled public scripture text.';
